server:
  port: 8000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://eu-de.appid.cloud.ibm.com/oauth/v4/78a538b6-6eca-4f61-8cea-506eb9b7c3db